version: '3.9'
volumes:
  volume-pgdata:


services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - public
    networks:
      cj:


  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=cj_proj
    volumes:
      - volume-pgdata:/var/lib/postgresql/data
    networks:
      cj:

  public:
    container_name: public
    build:
      context: django-site/
      dockerfile: ./Dockerfile.front
    ports:
      - 8000:8000
    environment:
      - DB_USER=django
      - DB_PWSD=django
      - DB_NAME=cj_proj
      - DB_HOST=db
      - DB_TYPE=pgsql
    depends_on:
      - db
      - api
    networks:
      cj:

  api:
    container_name: api
    build:
      context: django-site/
      dockerfile: ./Dockerfile.api
    ports:
      - 8001:8000  
    environment:
      - DB_USER=django
      - DB_PWSD=django
      - DB_NAME=cj_proj
      - DB_HOST=db
      - DB_TYPE=pgsql 
    depends_on:
      - db
    networks:
      cj:

networks:
  cj:









