FROM python:3.12-alpine

WORKDIR /web

COPY ./requirements.txt /web

RUN pip install -r requirements.txt

COPY ./entrypoint.sh /web
COPY ./CJ_Proj/CJ_Proj /web/CJ_Proj 
COPY ./CJ_Proj/api /web/api
COPY ./CJ_Proj/manage.py /web

ENTRYPOINT [ "./entrypoint.sh" ]