# Generated by Django 5.1 on 2024-09-04 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pret_cj',
            name='jeu',
        ),
        migrations.RemoveField(
            model_name='pret_cj',
            name='user',
        ),
        migrations.CreateModel(
            name='PretAnimInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_livre', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin_livre', models.DateTimeField(default=django.utils.timezone.now)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'livre')},
            },
        ),
        migrations.CreateModel(
            name='PretCJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_jeu', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin_jeu', models.DateTimeField(default=django.utils.timezone.now)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.jeux')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'jeu')},
            },
        ),
        migrations.DeleteModel(
            name='Pret_AnimINT',
        ),
        migrations.DeleteModel(
            name='Pret_CJ',
        ),
    ]
